name: 3-TAG-LOCAL

on:
  push:
    branches:
      - develop
      # - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set permissions for github.token.
permissions: write-all

jobs:

  # Job 1 - Create a tag for own repo using github.token.
  tagOwnRepo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create a tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git tag test-tag-$(date +%s)
          git push origin --tags
