name: 4-TAG-REMOTE

on:
  push:
    branches:
      - develop
      # - main
  # pull_request:
  #   branches:
  #     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set permissions for github.token.
# permissions: write-all

jobs:

  # Job 1 - Create a tag for remote repo.
  tagRemoteRepo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: rhod9rz-org/remote
      - name: Create a tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          timestamp=$(date +'%y%m%d-%H%M')
          git tag test-tag-${timestamp}
          git push origin --tags
