name: 5-PUSH-LOCAL

on:
  push:
    branches:
      - develop
      # - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set permissions for github.token.
permissions: write-all

jobs:

  # Job 1 - Push to a local repo
  pushToLocalRepo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone local
        uses: actions/checkout@v3
      - name: Push some code
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "rhod3rz@example.com"
          git config --global user.name "rhod3rz"
          timestamp=$(date +'%y%m%d-%H%M')
          echo "$timestamp" >> testfile.txt
          git add testfile.txt
          git commit -m "push to test file ($timestamp)"
          git push
