name: TAGS

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:




jobs:

  # Job 1 - Create a tag for own repo using github.token.
  tagOwnRepo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create a tag
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git tag test-tag-$(date +%s)
          git push origin --tags

  # Job 2 - Create a tag for remote repo using gh_pat
  tagRemoteRepo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone with PAT - Actions
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: rhod9rz-org/remote
      # - name: Create a tag
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   run: |
      #     git tag test-tag-$(date +%s)
      #     git push origin --tags
